[package]
name = "helio-pass-billboard"
version = "0.1.0"
edition = "2021"
description = "Helio render pass: helio-pass-billboard"
license = "MIT OR Apache-2.0"

[features]
default = ["gpu"]
gpu = []

[dependencies]
pulsar_reflection = { workspace = true }
helio-core  = { workspace = true }
wgpu      = { workspace = true }
bytemuck  = { workspace = true, features = ["derive"] }
pulsar_scenedb = { workspace = true }
pulsar_scenedb_derive = { workspace = true }

[[test]]
name = "scene_component"
path = "tests/scene_component.rs"
