[package]
name = "helio-pass-shadow-dirty"
version = "0.1.0"
edition = "2021"

[dependencies]
helio-core = { workspace = true }
helio-pass-gbuffer = { path = "../helio-pass-gbuffer" }
helio-pass-shadow-matrix = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
