[package]
name = "helio-pass-shadow-matrix"
version = "0.1.0"
edition = "2021"

[dependencies]
helio-core = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }

[dev-dependencies]
pollster = { workspace = true }
glam = { workspace = true }
helio-pass-forward-lit = { path = "../helio-pass-forward-lit" }
