[package]
name = "helio-pass-volumetric-fog"
version = "0.1.0"
edition = "2021"
description = "Helio render pass: helio-pass-volumetric-fog"
license = "MIT OR Apache-2.0"

[features]
default = ["gpu"]
gpu = []

[dependencies]
pulsar_reflection = { workspace = true }
helio-core = { workspace = true }
helio-pass-postprocess = { workspace = true }
helio-pass-shadow-matrix = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
pulsar_scenedb = { workspace = true }
pulsar_scenedb_derive = { workspace = true }

[dev-dependencies]
pollster = { workspace = true }
glam = { workspace = true }
