[package]
name = "helio-pass-gbuffer"
version = "0.1.0"
edition = "2021"
description = "Helio render pass: helio-pass-gbuffer"
license = "MIT OR Apache-2.0"

[features]
default = ["gpu"]
gpu = []

[dependencies]
helio      = { workspace = true }
helio-core  = { workspace = true }
libhelio  = { workspace = true }
glam      = { workspace = true }
wgpu      = { workspace = true }
bytemuck  = { workspace = true, features = ["derive"] }
log       = { workspace = true }
pulsar_scenedb = { git = "https://github.com/Far-Beyond-Pulsar/SceneDB", rev = "72291d0f211dc8826eb70339aeb0409be4270ad5", features = ["gpu"] }
pulsar_scenedb_derive = { git = "https://github.com/Far-Beyond-Pulsar/SceneDB", rev = "72291d0f211dc8826eb70339aeb0409be4270ad5" }
